---
name: Parse-Apache-ServerStatus
version: 0.08
author:
  - Jonny Schulz
abstract: Simple module to parse apache's server-status.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Accessor::Fast: 0
  LWP::UserAgent: 0
  Params::Validate: 0
  Test::More: 0
provides:
  Parse::Apache::ServerStatus:
    file: lib/Parse/Apache/ServerStatus.pm
    version: 0.08
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
